unit Icons;

interface

const
  xpm_new: array of PChar = (
    '16 16 3 1',
    '  c None',
    'B c #000000000000',
    'W c #FFFFFFFFFFFF',
    '                ',
    '  BBBBBBBBB     ',
    '  BWWWWWWWBB    ',
    '  BWWWWWWWBWB   ',
    '  BWWWWWWWBBBB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BWWWWWWWWWWB  ',
    '  BBBBBBBBBBBB  ',
    '                ');

  xpm_open: array of PChar = (
    '16 16 4 1',
    '  c None',
    'B c #000000000000',
    'Y c #FFFFFFFF0000',
    'y c #999999990000',
    '                ',
    '          BBB   ',
    '  BBBBB  B   BB ',
    '  BYYYB      BB ',
    ' BYYYYYBBBBB    ',
    ' BYYYYYYYYYB    ',
    ' BYYYYYYYYYB    ',
    ' BYYYYYYYYYB    ',
    ' BYYBBBBBBBBBBB ',
    ' BYYByyyyyyyyyB ',
    ' BYByyyyyyyyyB  ',
    ' BYByyyyyyyyyB  ',
    ' BByyyyyyyyyB   ',
    ' BByyyyyyyyyB   ',
    ' BBBBBBBBBBB    ',
    '                ');

  xpm_cut: array of PChar = (
    '16 16 2 1',
    '  c None',
    'B c #000000000000',
    '                ',
    '                ',
    '     B   B      ',
    '     B   B      ',
    '      B B       ',
    '      B B       ',
    '       B        ',
    '       B        ',
    '      B B       ',
    '    BBB BBB     ',
    '   B  B B  B    ',
    '   B  B B  B    ',
    '   B  B  BB     ',
    '    BB          ',
    '                ',
    '                ');

  xpm_copy: array of PChar = (
    '16 16 4 1',
    '  c None',
    'B c #000000000000',
    'W c #FFFFFFFFFFFF',
    'G c #666666666666',
    '                ',
    ' BBBBBBB        ',
    ' BWWWWBWB       ',
    ' BWGGWBBB       ',
    ' BWWWWWWB       ',
    ' BWGGGGWB       ',
    ' BWWWWBBBBBBB   ',
    ' BWGGGBWWWWBWB  ',
    ' BWWWWBWGGWBBB  ',
    ' BBBBBBWWWWWWB  ',
    '      BWGGGGWB  ',
    '      BWWWWWWB  ',
    '      BWGGGGWB  ',
    '      BWWWWWWB  ',
    '      BBBBBBBB  ',
    '                ');

  xpm_bold: array of PChar = (
    '16 16 2 1',
    '  c None',
    'B c #000000000000',
    '                ',
    ' BBBBBBBBBB     ',
    '  BBBBBBBBBBB   ',
    '  BBBBBBBBBBBB  ',
    '  BBB     BBBB  ',
    '  BBB      BBB  ',
    '  BBB     BBBB  ',
    '  BBBBBBBBBBB   ',
    '  BBBBBBBBBBB   ',
    '  BBB     BBBB  ',
    '  BBB      BBB  ',
    '  BBB     BBBB  ',
    '  BBBBBBBBBBBB  ',
    ' BBBBBBBBBBBB   ',
    ' BBBBBBBBBB     ',
    '                ');

  xpm_italics: array of PChar = (
    '16 16 2 1',
    '  c None',
    'B c #000000000000',
    '                ',
    '                ',
    '     BBBBBBBBBB ',
    '         BB     ',
    '         BB     ',
    '        BB      ',
    '        BB      ',
    '        BB      ',
    '       BB       ',
    '       BB       ',
    '      BB        ',
    '      BB        ',
    '      BB        ',
    '     BBB        ',
    ' BBBBBBBBBB     ',
    '                ');

  xpm_underline: array of PChar = (
    '16 16 2 1',
    '  c None',
    'B c #000000000000',
    '                ',
    '                ',
    '   BBBB  BBBB   ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BB    BB    ',
    '    BBBBBBBB    ',
    '     BBBBBB B   ',
    '                ',
    '  BBBBBBBBBBBB  ',
    '                ');

implementation

end.
