  //{%MainUnit sdl3.pas}
      {$include common_gtk.inc}



  {$include SDL3_stdinc.inc}
  {$include SDL3_guid.inc}
  {$include SDL3_scancode.inc}
  {$include SDL3_mutex.inc}
  {$include SDL3_touch.inc}
  {$include SDL3_blendmode.inc}
  {$include SDL3_init.inc}
  {$include SDL3_assert.inc}
  {$include SDL3_locale.inc}
  {$include SDL3_thread.inc}
  {$include SDL3_error.inc}
  {$include SDL3_filesystem.inc}

  {$include SDL3_log.inc}
  {$include SDL3_platform.inc}
  {$include SDL3_misc.inc}
  {$include SDL3_power.inc}
  {$include SDL3_timer.inc}
  {$include SDL3_time.inc}
  {$include SDL3_pixels.inc}
  {$include SDL3_properties.inc}
  {$include SDL3_storage.inc}
  {$include SDL3_rect.inc}
  // {$include SDL3_rwops.inc}
  {$include sdl3_iostream.inc}
  {$include SDL3_version.inc}
  {$include SDL3_clipboard.inc}
  {$include SDL3_atomic.inc}
  {$include SDL3_cpuinfo.inc}
  {$include SDL3_hints.inc}
  {$include SDL3_hidapi.inc}
  {$include SDL3_loadso.inc}
  {$include SDL3_sensor.inc}
  {$include SDL3_pen.inc}
  {$include SDL3_audio.inc}
  {$include SDL3_surface.inc}
  {$include SDL3_video.inc}
  {$include SDL3_camera.inc}
  {$include SDL3_messagebox.inc}
  {$include SDL3_dialog.inc}
  {$include SDL3_metal.inc}
  {$include SDL3_keycode.inc}
  {$include SDL3_keyboard.inc}
  {$include SDL3_mouse.inc}
  {$include SDL3_joystick.inc}
  {$include SDL3_gamepad.inc}
  {$include SDL3_haptic.inc}
  {$include SDL3_events.inc}
  // {$include SDL3_quit.inc}
  {$include SDL3_render.inc}
  {$include SDL3_system.inc}
