
unit gdkenums;

interface

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}

type
  PGdkGLAPI = ^TGdkGLAPI;
  TGdkGLAPI = longint;

const
  GDK_GL_API_GL = 1 shl 0;
  GDK_GL_API_GLES = 1 shl 1;

type
  PGdkGravity = ^TGdkGravity;
  TGdkGravity = longint;

const
  GDK_GRAVITY_NORTH_WEST = 1;
  GDK_GRAVITY_NORTH = 2;
  GDK_GRAVITY_NORTH_EAST = 3;
  GDK_GRAVITY_WEST = 4;
  GDK_GRAVITY_CENTER = 5;
  GDK_GRAVITY_EAST = 6;
  GDK_GRAVITY_SOUTH_WEST = 7;
  GDK_GRAVITY_SOUTH = 8;
  GDK_GRAVITY_SOUTH_EAST = 9;
  GDK_GRAVITY_STATIC = 10;

type
  PGdkModifierType = ^TGdkModifierType;
  TGdkModifierType = longint;

const
  GDK_NO_MODIFIER_MASK = 0;
  GDK_SHIFT_MASK = 1 shl 0;
  GDK_LOCK_MASK = 1 shl 1;
  GDK_CONTROL_MASK = 1 shl 2;
  GDK_ALT_MASK = 1 shl 3;
  GDK_BUTTON1_MASK = 1 shl 8;
  GDK_BUTTON2_MASK = 1 shl 9;
  GDK_BUTTON3_MASK = 1 shl 10;
  GDK_BUTTON4_MASK = 1 shl 11;
  GDK_BUTTON5_MASK = 1 shl 12;
  GDK_SUPER_MASK = 1 shl 26;
  GDK_HYPER_MASK = 1 shl 27;
  GDK_META_MASK = 1 shl 28;
  GDK_MODIFIER_MASK = ((((((((((GDK_SHIFT_MASK or GDK_LOCK_MASK) or GDK_CONTROL_MASK) or GDK_ALT_MASK) or GDK_SUPER_MASK) or GDK_HYPER_MASK) or GDK_META_MASK) or GDK_BUTTON1_MASK) or GDK_BUTTON2_MASK) or GDK_BUTTON3_MASK) or GDK_BUTTON4_MASK) or GDK_BUTTON5_MASK;

type
  PGdkDmabufError = ^TGdkDmabufError;
  TGdkDmabufError = longint;

const
  GDK_DMABUF_ERROR_NOT_AVAILABLE = 0;
  GDK_DMABUF_ERROR_UNSUPPORTED_FORMAT = 1;
  GDK_DMABUF_ERROR_CREATION_FAILED = 2;

type
  PGdkGLError = ^TGdkGLError;
  TGdkGLError = longint;

const
  GDK_GL_ERROR_NOT_AVAILABLE = 0;
  GDK_GL_ERROR_UNSUPPORTED_FORMAT = 1;
  GDK_GL_ERROR_UNSUPPORTED_PROFILE = 2;
  GDK_GL_ERROR_COMPILATION_FAILED = 3;
  GDK_GL_ERROR_LINK_FAILED = 4;

type
  PGdkVulkanError = ^TGdkVulkanError;
  TGdkVulkanError = longint;

const
  GDK_VULKAN_ERROR_UNSUPPORTED = 0;
  GDK_VULKAN_ERROR_NOT_AVAILABLE = 1;

type
  PGdkAxisUse = ^TGdkAxisUse;
  TGdkAxisUse = longint;

const
  GDK_AXIS_IGNORE = 0;
  GDK_AXIS_X = 1;
  GDK_AXIS_Y = 2;
  GDK_AXIS_DELTA_X = 3;
  GDK_AXIS_DELTA_Y = 4;
  GDK_AXIS_PRESSURE = 5;
  GDK_AXIS_XTILT = 6;
  GDK_AXIS_YTILT = 7;
  GDK_AXIS_WHEEL = 8;
  GDK_AXIS_DISTANCE = 9;
  GDK_AXIS_ROTATION = 10;
  GDK_AXIS_SLIDER = 11;
  GDK_AXIS_LAST = 12;

type
  PGdkAxisFlags = ^TGdkAxisFlags;
  TGdkAxisFlags = longint;

const
  GDK_AXIS_FLAG_X = 1 shl GDK_AXIS_X;
  GDK_AXIS_FLAG_Y = 1 shl GDK_AXIS_Y;
  GDK_AXIS_FLAG_DELTA_X = 1 shl GDK_AXIS_DELTA_X;
  GDK_AXIS_FLAG_DELTA_Y = 1 shl GDK_AXIS_DELTA_Y;
  GDK_AXIS_FLAG_PRESSURE = 1 shl GDK_AXIS_PRESSURE;
  GDK_AXIS_FLAG_XTILT = 1 shl GDK_AXIS_XTILT;
  GDK_AXIS_FLAG_YTILT = 1 shl GDK_AXIS_YTILT;
  GDK_AXIS_FLAG_WHEEL = 1 shl GDK_AXIS_WHEEL;
  GDK_AXIS_FLAG_DISTANCE = 1 shl GDK_AXIS_DISTANCE;
  GDK_AXIS_FLAG_ROTATION = 1 shl GDK_AXIS_ROTATION;
  GDK_AXIS_FLAG_SLIDER = 1 shl GDK_AXIS_SLIDER;

type
  PGdkDragAction = ^TGdkDragAction;
  TGdkDragAction = longint;

const
  GDK_ACTION_COPY = 1 shl 0;
  GDK_ACTION_MOVE = 1 shl 1;
  GDK_ACTION_LINK = 1 shl 2;
  GDK_ACTION_ASK = 1 shl 3;
  GDK_ACTION_ALL = (GDK_ACTION_COPY or GDK_ACTION_MOVE) or GDK_ACTION_LINK;

type
  PGdkMemoryFormat = ^TGdkMemoryFormat;
  TGdkMemoryFormat = longint;

const
  GDK_MEMORY_B8G8R8A8_PREMULTIPLIED = 0;
  GDK_MEMORY_A8R8G8B8_PREMULTIPLIED = 1;
  GDK_MEMORY_R8G8B8A8_PREMULTIPLIED = 2;
  GDK_MEMORY_B8G8R8A8 = 3;
  GDK_MEMORY_A8R8G8B8 = 4;
  GDK_MEMORY_R8G8B8A8 = 5;
  GDK_MEMORY_A8B8G8R8 = 6;
  GDK_MEMORY_R8G8B8 = 7;
  GDK_MEMORY_B8G8R8 = 8;
  GDK_MEMORY_R16G16B16 = 9;
  GDK_MEMORY_R16G16B16A16_PREMULTIPLIED = 10;
  GDK_MEMORY_R16G16B16A16 = 11;
  GDK_MEMORY_R16G16B16_FLOAT = 12;
  GDK_MEMORY_R16G16B16A16_FLOAT_PREMULTIPLIED = 13;
  GDK_MEMORY_R16G16B16A16_FLOAT = 14;
  GDK_MEMORY_R32G32B32_FLOAT = 15;
  GDK_MEMORY_R32G32B32A32_FLOAT_PREMULTIPLIED = 16;
  GDK_MEMORY_R32G32B32A32_FLOAT = 17;
  GDK_MEMORY_G8A8_PREMULTIPLIED = 18;
  GDK_MEMORY_G8A8 = 19;
  GDK_MEMORY_G8 = 20;
  GDK_MEMORY_G16A16_PREMULTIPLIED = 21;
  GDK_MEMORY_G16A16 = 22;
  GDK_MEMORY_G16 = 23;
  GDK_MEMORY_A8 = 24;
  GDK_MEMORY_A16 = 25;
  GDK_MEMORY_A16_FLOAT = 26;
  GDK_MEMORY_A32_FLOAT = 27;
  GDK_MEMORY_A8B8G8R8_PREMULTIPLIED = 28;
  GDK_MEMORY_B8G8R8X8 = 29;
  GDK_MEMORY_X8R8G8B8 = 30;
  GDK_MEMORY_R8G8B8X8 = 31;
  GDK_MEMORY_X8B8G8R8 = 32;
  GDK_MEMORY_N_FORMATS = 33;


implementation


end.
