unit gtkenums;

interface

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}

type
  PGtkAlign = ^TGtkAlign;
  TGtkAlign = longint;

const
  GTK_ALIGN_FILL = 0;
  GTK_ALIGN_START = 1;
  GTK_ALIGN_END = 2;
  GTK_ALIGN_CENTER = 3;
  GTK_ALIGN_BASELINE_FILL = 4;
  GTK_ALIGN_BASELINE = 5;
  GTK_ALIGN_BASELINE_CENTER = 6;

type
  PGtkArrowType = ^TGtkArrowType;
  TGtkArrowType = longint;

const
  GTK_ARROW_UP = 0;
  GTK_ARROW_DOWN = 1;
  GTK_ARROW_LEFT = 2;
  GTK_ARROW_RIGHT = 3;
  GTK_ARROW_NONE = 4;

type
  PGtkBaselinePosition = ^TGtkBaselinePosition;
  TGtkBaselinePosition = longint;

const
  GTK_BASELINE_POSITION_TOP = 0;
  GTK_BASELINE_POSITION_CENTER = 1;
  GTK_BASELINE_POSITION_BOTTOM = 2;

type
  PGtkContentFit = ^TGtkContentFit;
  TGtkContentFit = longint;

const
  GTK_CONTENT_FIT_FILL = 0;
  GTK_CONTENT_FIT_CONTAIN = 1;
  GTK_CONTENT_FIT_COVER = 2;
  GTK_CONTENT_FIT_SCALE_DOWN = 3;

type
  PGtkDeleteType = ^TGtkDeleteType;
  TGtkDeleteType = longint;

const
  GTK_DELETE_CHARS = 0;
  GTK_DELETE_WORD_ENDS = 1;
  GTK_DELETE_WORDS = 2;
  GTK_DELETE_DISPLAY_LINES = 3;
  GTK_DELETE_DISPLAY_LINE_ENDS = 4;
  GTK_DELETE_PARAGRAPH_ENDS = 5;
  GTK_DELETE_PARAGRAPHS = 6;
  GTK_DELETE_WHITESPACE = 7;

type
  PGtkDirectionType = ^TGtkDirectionType;
  TGtkDirectionType = longint;

const
  GTK_DIR_TAB_FORWARD = 0;
  GTK_DIR_TAB_BACKWARD = 1;
  GTK_DIR_UP = 2;
  GTK_DIR_DOWN = 3;
  GTK_DIR_LEFT = 4;
  GTK_DIR_RIGHT = 5;

type
  PGtkIconSize = ^TGtkIconSize;
  TGtkIconSize = longint;

const
  GTK_ICON_SIZE_INHERIT = 0;
  GTK_ICON_SIZE_NORMAL = 1;
  GTK_ICON_SIZE_LARGE = 2;

type
  PGtkSensitivityType = ^TGtkSensitivityType;
  TGtkSensitivityType = longint;

const
  GTK_SENSITIVITY_AUTO = 0;
  GTK_SENSITIVITY_ON = 1;
  GTK_SENSITIVITY_OFF = 2;

type
  PGtkTextDirection = ^TGtkTextDirection;
  TGtkTextDirection = longint;

const
  GTK_TEXT_DIR_NONE = 0;
  GTK_TEXT_DIR_LTR = 1;
  GTK_TEXT_DIR_RTL = 2;

type
  PGtkJustification = ^TGtkJustification;
  TGtkJustification = longint;

const
  GTK_JUSTIFY_LEFT = 0;
  GTK_JUSTIFY_RIGHT = 1;
  GTK_JUSTIFY_CENTER = 2;
  GTK_JUSTIFY_FILL = 3;

type
  PGtkListTabBehavior = ^TGtkListTabBehavior;
  TGtkListTabBehavior = longint;

const
  GTK_LIST_TAB_ALL = 0;
  GTK_LIST_TAB_ITEM = 1;
  GTK_LIST_TAB_CELL = 2;

type
  PGtkListScrollFlags = ^TGtkListScrollFlags;
  TGtkListScrollFlags = longint;

const
  GTK_LIST_SCROLL_NONE = 0;
  GTK_LIST_SCROLL_FOCUS = 1 shl 0;
  GTK_LIST_SCROLL_SELECT = 1 shl 1;

type
  PGtkMessageType = ^TGtkMessageType;
  TGtkMessageType = longint;

const
  GTK_MESSAGE_INFO = 0;
  GTK_MESSAGE_WARNING = 1;
  GTK_MESSAGE_QUESTION = 2;
  GTK_MESSAGE_ERROR = 3;
  GTK_MESSAGE_OTHER = 4;

type
  PGtkMovementStep = ^TGtkMovementStep;
  TGtkMovementStep = longint;

const
  GTK_MOVEMENT_LOGICAL_POSITIONS = 0;
  GTK_MOVEMENT_VISUAL_POSITIONS = 1;
  GTK_MOVEMENT_WORDS = 2;
  GTK_MOVEMENT_DISPLAY_LINES = 3;
  GTK_MOVEMENT_DISPLAY_LINE_ENDS = 4;
  GTK_MOVEMENT_PARAGRAPHS = 5;
  GTK_MOVEMENT_PARAGRAPH_ENDS = 6;
  GTK_MOVEMENT_PAGES = 7;
  GTK_MOVEMENT_BUFFER_ENDS = 8;
  GTK_MOVEMENT_HORIZONTAL_PAGES = 9;

type
  PGtkNaturalWrapMode = ^TGtkNaturalWrapMode;
  TGtkNaturalWrapMode = longint;

const
  GTK_NATURAL_WRAP_INHERIT = 0;
  GTK_NATURAL_WRAP_NONE = 1;
  GTK_NATURAL_WRAP_WORD = 2;

type
  PGtkScrollStep = ^TGtkScrollStep;
  TGtkScrollStep = longint;

const
  GTK_SCROLL_STEPS = 0;
  GTK_SCROLL_PAGES = 1;
  GTK_SCROLL_ENDS = 2;
  GTK_SCROLL_HORIZONTAL_STEPS = 3;
  GTK_SCROLL_HORIZONTAL_PAGES = 4;
  GTK_SCROLL_HORIZONTAL_ENDS = 5;

type
  PGtkOrientation = ^TGtkOrientation;
  TGtkOrientation = longint;

const
  GTK_ORIENTATION_HORIZONTAL = 0;
  GTK_ORIENTATION_VERTICAL = 1;

type
  PGtkOverflow = ^TGtkOverflow;
  TGtkOverflow = longint;

const
  GTK_OVERFLOW_VISIBLE = 0;
  GTK_OVERFLOW_HIDDEN = 1;

type
  PGtkPackType = ^TGtkPackType;
  TGtkPackType = longint;

const
  GTK_PACK_START = 0;
  GTK_PACK_END = 1;

type
  PGtkPositionType = ^TGtkPositionType;
  TGtkPositionType = longint;

const
  GTK_POS_LEFT = 0;
  GTK_POS_RIGHT = 1;
  GTK_POS_TOP = 2;
  GTK_POS_BOTTOM = 3;

type
  PGtkScrollType = ^TGtkScrollType;
  TGtkScrollType = longint;

const
  GTK_SCROLL_NONE = 0;
  GTK_SCROLL_JUMP = 1;
  GTK_SCROLL_STEP_BACKWARD = 2;
  GTK_SCROLL_STEP_FORWARD = 3;
  GTK_SCROLL_PAGE_BACKWARD = 4;
  GTK_SCROLL_PAGE_FORWARD = 5;
  GTK_SCROLL_STEP_UP = 6;
  GTK_SCROLL_STEP_DOWN = 7;
  GTK_SCROLL_PAGE_UP = 8;
  GTK_SCROLL_PAGE_DOWN = 9;
  GTK_SCROLL_STEP_LEFT = 10;
  GTK_SCROLL_STEP_RIGHT = 11;
  GTK_SCROLL_PAGE_LEFT = 12;
  GTK_SCROLL_PAGE_RIGHT = 13;
  GTK_SCROLL_START = 14;
  GTK_SCROLL_END = 15;

type
  PGtkSelectionMode = ^TGtkSelectionMode;
  TGtkSelectionMode = longint;

const
  GTK_SELECTION_NONE = 0;
  GTK_SELECTION_SINGLE = 1;
  GTK_SELECTION_BROWSE = 2;
  GTK_SELECTION_MULTIPLE = 3;

type
  PGtkWrapMode = ^TGtkWrapMode;
  TGtkWrapMode = longint;

const
  GTK_WRAP_NONE = 0;
  GTK_WRAP_CHAR = 1;
  GTK_WRAP_WORD = 2;
  GTK_WRAP_WORD_CHAR = 3;

type
  PGtkSortType = ^TGtkSortType;
  TGtkSortType = longint;

const
  GTK_SORT_ASCENDING = 0;
  GTK_SORT_DESCENDING = 1;

type
  PGtkPrintPages = ^TGtkPrintPages;
  TGtkPrintPages = longint;

const
  GTK_PRINT_PAGES_ALL = 0;
  GTK_PRINT_PAGES_CURRENT = 1;
  GTK_PRINT_PAGES_RANGES = 2;
  GTK_PRINT_PAGES_SELECTION = 3;

type
  PGtkPageSet = ^TGtkPageSet;
  TGtkPageSet = longint;

const
  GTK_PAGE_SET_ALL = 0;
  GTK_PAGE_SET_EVEN = 1;
  GTK_PAGE_SET_ODD = 2;

type
  PGtkNumberUpLayout = ^TGtkNumberUpLayout;
  TGtkNumberUpLayout = longint;

const
  GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM = 0;
  GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP = 1;
  GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM = 2;
  GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP = 3;
  GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT = 4;
  GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT = 5;
  GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT = 6;
  GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT = 7;

type
  PGtkOrdering = ^TGtkOrdering;
  TGtkOrdering = longint;

const
  GTK_ORDERING_SMALLER = -(1);
  GTK_ORDERING_EQUAL = 0;
  GTK_ORDERING_LARGER = 1;
  {$ifdef __GI_SCANNER__}

function gtk_ordering_from_cmpfunc(cmpfunc_result: longint): TGtkOrdering; cdecl; external;
{$else}
{*
 * gtk_ordering_from_cmpfunc: (skip)
 * @cmpfunc_result: Result of a comparison function
 *
 * Converts the result of a `GCompareFunc` like strcmp() to a
 * `GtkOrdering` value.
 *
 * Returns: the corresponding `GtkOrdering`
 * }
{static inline GtkOrdering }
{gtk_ordering_from_cmpfunc (int cmpfunc_result) }
{ }
{  return (GtkOrdering) ((cmpfunc_result > 0) - (cmpfunc_result < 0)); }
{ }
{$endif}
type
  PGtkPageOrientation = ^TGtkPageOrientation;
  TGtkPageOrientation = longint;

const
  GTK_PAGE_ORIENTATION_PORTRAIT = 0;
  GTK_PAGE_ORIENTATION_LANDSCAPE = 1;
  GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT = 2;
  GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE = 3;

type
  PGtkPrintQuality = ^TGtkPrintQuality;
  TGtkPrintQuality = longint;

const
  GTK_PRINT_QUALITY_LOW = 0;
  GTK_PRINT_QUALITY_NORMAL = 1;
  GTK_PRINT_QUALITY_HIGH = 2;
  GTK_PRINT_QUALITY_DRAFT = 3;

type
  PGtkPrintDuplex = ^TGtkPrintDuplex;
  TGtkPrintDuplex = longint;

const
  GTK_PRINT_DUPLEX_SIMPLEX = 0;
  GTK_PRINT_DUPLEX_HORIZONTAL = 1;
  GTK_PRINT_DUPLEX_VERTICAL = 2;

type
  PGtkUnit = ^TGtkUnit;
  TGtkUnit = longint;

const
  GTK_UNIT_NONE = 0;
  GTK_UNIT_POINTS = 1;
  GTK_UNIT_INCH = 2;
  GTK_UNIT_MM = 3;

  GTK_UNIT_PIXEL = GTK_UNIT_NONE;

type
  PGtkTreeViewGridLines = ^TGtkTreeViewGridLines;
  TGtkTreeViewGridLines = longint;

const
  GTK_TREE_VIEW_GRID_LINES_NONE = 0;
  GTK_TREE_VIEW_GRID_LINES_HORIZONTAL = 1;
  GTK_TREE_VIEW_GRID_LINES_VERTICAL = 2;
  GTK_TREE_VIEW_GRID_LINES_BOTH = 3;

type
  PGtkSizeGroupMode = ^TGtkSizeGroupMode;
  TGtkSizeGroupMode = longint;

const
  GTK_SIZE_GROUP_NONE = 0;
  GTK_SIZE_GROUP_HORIZONTAL = 1;
  GTK_SIZE_GROUP_VERTICAL = 2;
  GTK_SIZE_GROUP_BOTH = 3;

type
  PGtkSizeRequestMode = ^TGtkSizeRequestMode;
  TGtkSizeRequestMode = longint;

const
  GTK_SIZE_REQUEST_HEIGHT_FOR_WIDTH = 0;
  GTK_SIZE_REQUEST_WIDTH_FOR_HEIGHT = 1;
  GTK_SIZE_REQUEST_CONSTANT_SIZE = 2;

type
  PGtkScrollablePolicy = ^TGtkScrollablePolicy;
  TGtkScrollablePolicy = longint;

const
  GTK_SCROLL_MINIMUM = 0;
  GTK_SCROLL_NATURAL = 1;

type
  PGtkStateFlags = ^TGtkStateFlags;
  TGtkStateFlags = longint;

const
  GTK_STATE_FLAG_NORMAL = 0;
  GTK_STATE_FLAG_ACTIVE = 1 shl 0;
  GTK_STATE_FLAG_PRELIGHT = 1 shl 1;
  GTK_STATE_FLAG_SELECTED = 1 shl 2;
  GTK_STATE_FLAG_INSENSITIVE = 1 shl 3;
  GTK_STATE_FLAG_INCONSISTENT = 1 shl 4;
  GTK_STATE_FLAG_FOCUSED = 1 shl 5;
  GTK_STATE_FLAG_BACKDROP = 1 shl 6;
  GTK_STATE_FLAG_DIR_LTR = 1 shl 7;
  GTK_STATE_FLAG_DIR_RTL = 1 shl 8;
  GTK_STATE_FLAG_LINK = 1 shl 9;
  GTK_STATE_FLAG_VISITED = 1 shl 10;
  GTK_STATE_FLAG_CHECKED = 1 shl 11;
  GTK_STATE_FLAG_DROP_ACTIVE = 1 shl 12;
  GTK_STATE_FLAG_FOCUS_VISIBLE = 1 shl 13;
  GTK_STATE_FLAG_FOCUS_WITHIN = 1 shl 14;

type
  PGtkBorderStyle = ^TGtkBorderStyle;
  TGtkBorderStyle = longint;

const
  GTK_BORDER_STYLE_NONE = 0;
  GTK_BORDER_STYLE_HIDDEN = 1;
  GTK_BORDER_STYLE_SOLID = 2;
  GTK_BORDER_STYLE_INSET = 3;
  GTK_BORDER_STYLE_OUTSET = 4;
  GTK_BORDER_STYLE_DOTTED = 5;
  GTK_BORDER_STYLE_DASHED = 6;
  GTK_BORDER_STYLE_DOUBLE = 7;
  GTK_BORDER_STYLE_GROOVE = 8;
  GTK_BORDER_STYLE_RIDGE = 9;

type
  PGtkLevelBarMode = ^TGtkLevelBarMode;
  TGtkLevelBarMode = longint;

const
  GTK_LEVEL_BAR_MODE_CONTINUOUS = 0;
  GTK_LEVEL_BAR_MODE_DISCRETE = 1;

type
  PGtkInputPurpose = ^TGtkInputPurpose;
  TGtkInputPurpose = longint;

const
  GTK_INPUT_PURPOSE_FREE_FORM = 0;
  GTK_INPUT_PURPOSE_ALPHA = 1;
  GTK_INPUT_PURPOSE_DIGITS = 2;
  GTK_INPUT_PURPOSE_NUMBER = 3;
  GTK_INPUT_PURPOSE_PHONE = 4;
  GTK_INPUT_PURPOSE_URL = 5;
  GTK_INPUT_PURPOSE_EMAIL = 6;
  GTK_INPUT_PURPOSE_NAME = 7;
  GTK_INPUT_PURPOSE_PASSWORD = 8;
  GTK_INPUT_PURPOSE_PIN = 9;
  GTK_INPUT_PURPOSE_TERMINAL = 10;

type
  PGtkInputHints = ^TGtkInputHints;
  TGtkInputHints = longint;

const
  GTK_INPUT_HINT_NONE = 0;
  GTK_INPUT_HINT_SPELLCHECK = 1 shl 0;
  GTK_INPUT_HINT_NO_SPELLCHECK = 1 shl 1;
  GTK_INPUT_HINT_WORD_COMPLETION = 1 shl 2;
  GTK_INPUT_HINT_LOWERCASE = 1 shl 3;
  GTK_INPUT_HINT_UPPERCASE_CHARS = 1 shl 4;
  GTK_INPUT_HINT_UPPERCASE_WORDS = 1 shl 5;
  GTK_INPUT_HINT_UPPERCASE_SENTENCES = 1 shl 6;
  GTK_INPUT_HINT_INHIBIT_OSK = 1 shl 7;
  GTK_INPUT_HINT_VERTICAL_WRITING = 1 shl 8;
  GTK_INPUT_HINT_EMOJI = 1 shl 9;
  GTK_INPUT_HINT_NO_EMOJI = 1 shl 10;
  GTK_INPUT_HINT_PRIVATE = 1 shl 11;

type
  PGtkPropagationPhase = ^TGtkPropagationPhase;
  TGtkPropagationPhase = longint;

const
  GTK_PHASE_NONE = 0;
  GTK_PHASE_CAPTURE = 1;
  GTK_PHASE_BUBBLE = 2;
  GTK_PHASE_TARGET = 3;

type
  PGtkPropagationLimit = ^TGtkPropagationLimit;
  TGtkPropagationLimit = longint;

const
  GTK_LIMIT_NONE = 0;
  GTK_LIMIT_SAME_NATIVE = 1;

type
  PGtkEventSequenceState = ^TGtkEventSequenceState;
  TGtkEventSequenceState = longint;

const
  GTK_EVENT_SEQUENCE_NONE = 0;
  GTK_EVENT_SEQUENCE_CLAIMED = 1;
  GTK_EVENT_SEQUENCE_DENIED = 2;

type
  PGtkPanDirection = ^TGtkPanDirection;
  TGtkPanDirection = longint;

const
  GTK_PAN_DIRECTION_LEFT = 0;
  GTK_PAN_DIRECTION_RIGHT = 1;
  GTK_PAN_DIRECTION_UP = 2;
  GTK_PAN_DIRECTION_DOWN = 3;

type
  PGtkShortcutScope = ^TGtkShortcutScope;
  TGtkShortcutScope = longint;

const
  GTK_SHORTCUT_SCOPE_LOCAL = 0;
  GTK_SHORTCUT_SCOPE_MANAGED = 1;
  GTK_SHORTCUT_SCOPE_GLOBAL = 2;

type
  PGtkPickFlags = ^TGtkPickFlags;
  TGtkPickFlags = longint;

const
  GTK_PICK_DEFAULT = 0;
  GTK_PICK_INSENSITIVE = 1 shl 0;
  GTK_PICK_NON_TARGETABLE = 1 shl 1;

type
  PGtkConstraintRelation = ^TGtkConstraintRelation;
  TGtkConstraintRelation = longint;

const
  GTK_CONSTRAINT_RELATION_LE = -(1);
  GTK_CONSTRAINT_RELATION_EQ = 0;
  GTK_CONSTRAINT_RELATION_GE = 1;

type
  PGtkConstraintStrength = ^TGtkConstraintStrength;
  TGtkConstraintStrength = longint;

const
  GTK_CONSTRAINT_STRENGTH_REQUIRED = 1001001000;
  GTK_CONSTRAINT_STRENGTH_STRONG = 1000000000;
  GTK_CONSTRAINT_STRENGTH_MEDIUM = 1000;
  GTK_CONSTRAINT_STRENGTH_WEAK = 1;

type
  PGtkConstraintAttribute = ^TGtkConstraintAttribute;
  TGtkConstraintAttribute = longint;

const
  GTK_CONSTRAINT_ATTRIBUTE_NONE = 0;
  GTK_CONSTRAINT_ATTRIBUTE_LEFT = 1;
  GTK_CONSTRAINT_ATTRIBUTE_RIGHT = 2;
  GTK_CONSTRAINT_ATTRIBUTE_TOP = 3;
  GTK_CONSTRAINT_ATTRIBUTE_BOTTOM = 4;
  GTK_CONSTRAINT_ATTRIBUTE_START = 5;
  GTK_CONSTRAINT_ATTRIBUTE_END = 6;
  GTK_CONSTRAINT_ATTRIBUTE_WIDTH = 7;
  GTK_CONSTRAINT_ATTRIBUTE_HEIGHT = 8;
  GTK_CONSTRAINT_ATTRIBUTE_CENTER_X = 9;
  GTK_CONSTRAINT_ATTRIBUTE_CENTER_Y = 10;
  GTK_CONSTRAINT_ATTRIBUTE_BASELINE = 11;

type
  PGtkConstraintVflParserError = ^TGtkConstraintVflParserError;
  TGtkConstraintVflParserError = longint;

const
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_SYMBOL = 0;
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_ATTRIBUTE = 1;
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_VIEW = 2;
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_METRIC = 3;
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_PRIORITY = 4;
  GTK_CONSTRAINT_VFL_PARSER_ERROR_INVALID_RELATION = 5;

type
  PGtkSystemSetting = ^TGtkSystemSetting;
  TGtkSystemSetting = longint;

const
  GTK_SYSTEM_SETTING_DPI = 0;
  GTK_SYSTEM_SETTING_FONT_NAME = 1;
  GTK_SYSTEM_SETTING_FONT_CONFIG = 2;
  GTK_SYSTEM_SETTING_DISPLAY = 3;
  GTK_SYSTEM_SETTING_ICON_THEME = 4;

type
  PGtkSymbolicColor = ^TGtkSymbolicColor;
  TGtkSymbolicColor = longint;

const
  GTK_SYMBOLIC_COLOR_FOREGROUND = 0;
  GTK_SYMBOLIC_COLOR_ERROR = 1;
  GTK_SYMBOLIC_COLOR_WARNING = 2;
  GTK_SYMBOLIC_COLOR_SUCCESS = 3;

type
  PGtkAccessibleRole = ^TGtkAccessibleRole;
  TGtkAccessibleRole = longint;

const
  GTK_ACCESSIBLE_ROLE_ALERT = 0;
  GTK_ACCESSIBLE_ROLE_ALERT_DIALOG = 1;
  GTK_ACCESSIBLE_ROLE_BANNER = 2;
  GTK_ACCESSIBLE_ROLE_BUTTON = 3;
  GTK_ACCESSIBLE_ROLE_CAPTION = 4;
  GTK_ACCESSIBLE_ROLE_CELL = 5;
  GTK_ACCESSIBLE_ROLE_CHECKBOX = 6;
  GTK_ACCESSIBLE_ROLE_COLUMN_HEADER = 7;
  GTK_ACCESSIBLE_ROLE_COMBO_BOX = 8;
  GTK_ACCESSIBLE_ROLE_COMMAND = 9;
  GTK_ACCESSIBLE_ROLE_COMPOSITE = 10;
  GTK_ACCESSIBLE_ROLE_DIALOG = 11;
  GTK_ACCESSIBLE_ROLE_DOCUMENT = 12;
  GTK_ACCESSIBLE_ROLE_FEED = 13;
  GTK_ACCESSIBLE_ROLE_FORM = 14;
  GTK_ACCESSIBLE_ROLE_GENERIC = 15;
  GTK_ACCESSIBLE_ROLE_GRID = 16;
  GTK_ACCESSIBLE_ROLE_GRID_CELL = 17;
  GTK_ACCESSIBLE_ROLE_GROUP = 18;
  GTK_ACCESSIBLE_ROLE_HEADING = 19;
  GTK_ACCESSIBLE_ROLE_IMG = 20;
  GTK_ACCESSIBLE_ROLE_INPUT = 21;
  GTK_ACCESSIBLE_ROLE_LABEL = 22;
  GTK_ACCESSIBLE_ROLE_LANDMARK = 23;
  GTK_ACCESSIBLE_ROLE_LEGEND = 24;
  GTK_ACCESSIBLE_ROLE_LINK = 25;
  GTK_ACCESSIBLE_ROLE_LIST = 26;
  GTK_ACCESSIBLE_ROLE_LIST_BOX = 27;
  GTK_ACCESSIBLE_ROLE_LIST_ITEM = 28;
  GTK_ACCESSIBLE_ROLE_LOG = 29;
  GTK_ACCESSIBLE_ROLE_MAIN = 30;
  GTK_ACCESSIBLE_ROLE_MARQUEE = 31;
  GTK_ACCESSIBLE_ROLE_MATH = 32;
  GTK_ACCESSIBLE_ROLE_METER = 33;
  GTK_ACCESSIBLE_ROLE_MENU = 34;
  GTK_ACCESSIBLE_ROLE_MENU_BAR = 35;
  GTK_ACCESSIBLE_ROLE_MENU_ITEM = 36;
  GTK_ACCESSIBLE_ROLE_MENU_ITEM_CHECKBOX = 37;
  GTK_ACCESSIBLE_ROLE_MENU_ITEM_RADIO = 38;
  GTK_ACCESSIBLE_ROLE_NAVIGATION = 39;
  GTK_ACCESSIBLE_ROLE_NONE = 40;
  GTK_ACCESSIBLE_ROLE_NOTE = 41;
  GTK_ACCESSIBLE_ROLE_OPTION = 42;
  GTK_ACCESSIBLE_ROLE_PRESENTATION = 43;
  GTK_ACCESSIBLE_ROLE_PROGRESS_BAR = 44;
  GTK_ACCESSIBLE_ROLE_RADIO = 45;
  GTK_ACCESSIBLE_ROLE_RADIO_GROUP = 46;
  GTK_ACCESSIBLE_ROLE_RANGE = 47;
  GTK_ACCESSIBLE_ROLE_REGION = 48;
  GTK_ACCESSIBLE_ROLE_ROW = 49;
  GTK_ACCESSIBLE_ROLE_ROW_GROUP = 50;
  GTK_ACCESSIBLE_ROLE_ROW_HEADER = 51;
  GTK_ACCESSIBLE_ROLE_SCROLLBAR = 52;
  GTK_ACCESSIBLE_ROLE_SEARCH = 53;
  GTK_ACCESSIBLE_ROLE_SEARCH_BOX = 54;
  GTK_ACCESSIBLE_ROLE_SECTION = 55;
  GTK_ACCESSIBLE_ROLE_SECTION_HEAD = 56;
  GTK_ACCESSIBLE_ROLE_SELECT = 57;
  GTK_ACCESSIBLE_ROLE_SEPARATOR = 58;
  GTK_ACCESSIBLE_ROLE_SLIDER = 59;
  GTK_ACCESSIBLE_ROLE_SPIN_BUTTON = 60;
  GTK_ACCESSIBLE_ROLE_STATUS = 61;
  GTK_ACCESSIBLE_ROLE_STRUCTURE = 62;
  GTK_ACCESSIBLE_ROLE_SWITCH = 63;
  GTK_ACCESSIBLE_ROLE_TAB = 64;
  GTK_ACCESSIBLE_ROLE_TABLE = 65;
  GTK_ACCESSIBLE_ROLE_TAB_LIST = 66;
  GTK_ACCESSIBLE_ROLE_TAB_PANEL = 67;
  GTK_ACCESSIBLE_ROLE_TEXT_BOX = 68;
  GTK_ACCESSIBLE_ROLE_TIME = 69;
  GTK_ACCESSIBLE_ROLE_TIMER = 70;
  GTK_ACCESSIBLE_ROLE_TOOLBAR = 71;
  GTK_ACCESSIBLE_ROLE_TOOLTIP = 72;
  GTK_ACCESSIBLE_ROLE_TREE = 73;
  GTK_ACCESSIBLE_ROLE_TREE_GRID = 74;
  GTK_ACCESSIBLE_ROLE_TREE_ITEM = 75;
  GTK_ACCESSIBLE_ROLE_WIDGET = 76;
  GTK_ACCESSIBLE_ROLE_WINDOW = 77;
  GTK_ACCESSIBLE_ROLE_TOGGLE_BUTTON = 78;
  GTK_ACCESSIBLE_ROLE_APPLICATION = 79;
  GTK_ACCESSIBLE_ROLE_PARAGRAPH = 80;
  GTK_ACCESSIBLE_ROLE_BLOCK_QUOTE = 81;
  GTK_ACCESSIBLE_ROLE_ARTICLE = 82;
  GTK_ACCESSIBLE_ROLE_COMMENT = 83;
  GTK_ACCESSIBLE_ROLE_TERMINAL = 84;

type
  PGtkAccessibleState = ^TGtkAccessibleState;
  TGtkAccessibleState = longint;

const
  GTK_ACCESSIBLE_STATE_BUSY = 0;
  GTK_ACCESSIBLE_STATE_CHECKED = 1;
  GTK_ACCESSIBLE_STATE_DISABLED = 2;
  GTK_ACCESSIBLE_STATE_EXPANDED = 3;
  GTK_ACCESSIBLE_STATE_HIDDEN = 4;
  GTK_ACCESSIBLE_STATE_INVALID = 5;
  GTK_ACCESSIBLE_STATE_PRESSED = 6;
  GTK_ACCESSIBLE_STATE_SELECTED = 7;
  GTK_ACCESSIBLE_STATE_VISITED = 8;
  GTK_ACCESSIBLE_VALUE_UNDEFINED = -(1);

type
  PGtkAccessibleProperty = ^TGtkAccessibleProperty;
  TGtkAccessibleProperty = longint;

const
  GTK_ACCESSIBLE_PROPERTY_AUTOCOMPLETE = 0;
  GTK_ACCESSIBLE_PROPERTY_DESCRIPTION = 1;
  GTK_ACCESSIBLE_PROPERTY_HAS_POPUP = 2;
  GTK_ACCESSIBLE_PROPERTY_KEY_SHORTCUTS = 3;
  GTK_ACCESSIBLE_PROPERTY_LABEL = 4;
  GTK_ACCESSIBLE_PROPERTY_LEVEL = 5;
  GTK_ACCESSIBLE_PROPERTY_MODAL = 6;
  GTK_ACCESSIBLE_PROPERTY_MULTI_LINE = 7;
  GTK_ACCESSIBLE_PROPERTY_MULTI_SELECTABLE = 8;
  GTK_ACCESSIBLE_PROPERTY_ORIENTATION = 9;
  GTK_ACCESSIBLE_PROPERTY_PLACEHOLDER = 10;
  GTK_ACCESSIBLE_PROPERTY_READ_ONLY = 11;
  GTK_ACCESSIBLE_PROPERTY_REQUIRED = 12;
  GTK_ACCESSIBLE_PROPERTY_ROLE_DESCRIPTION = 13;
  GTK_ACCESSIBLE_PROPERTY_SORT = 14;
  GTK_ACCESSIBLE_PROPERTY_VALUE_MAX = 15;
  GTK_ACCESSIBLE_PROPERTY_VALUE_MIN = 16;
  GTK_ACCESSIBLE_PROPERTY_VALUE_NOW = 17;
  GTK_ACCESSIBLE_PROPERTY_VALUE_TEXT = 18;

type
  PGtkAccessibleRelation = ^TGtkAccessibleRelation;
  TGtkAccessibleRelation = longint;

const
  GTK_ACCESSIBLE_RELATION_ACTIVE_DESCENDANT = 0;
  GTK_ACCESSIBLE_RELATION_COL_COUNT = 1;
  GTK_ACCESSIBLE_RELATION_COL_INDEX = 2;
  GTK_ACCESSIBLE_RELATION_COL_INDEX_TEXT = 3;
  GTK_ACCESSIBLE_RELATION_COL_SPAN = 4;
  GTK_ACCESSIBLE_RELATION_CONTROLS = 5;
  GTK_ACCESSIBLE_RELATION_DESCRIBED_BY = 6;
  GTK_ACCESSIBLE_RELATION_DETAILS = 7;
  GTK_ACCESSIBLE_RELATION_ERROR_MESSAGE = 8;
  GTK_ACCESSIBLE_RELATION_FLOW_TO = 9;
  GTK_ACCESSIBLE_RELATION_LABELLED_BY = 10;
  GTK_ACCESSIBLE_RELATION_OWNS = 11;
  GTK_ACCESSIBLE_RELATION_POS_IN_SET = 12;
  GTK_ACCESSIBLE_RELATION_ROW_COUNT = 13;
  GTK_ACCESSIBLE_RELATION_ROW_INDEX = 14;
  GTK_ACCESSIBLE_RELATION_ROW_INDEX_TEXT = 15;
  GTK_ACCESSIBLE_RELATION_ROW_SPAN = 16;
  GTK_ACCESSIBLE_RELATION_SET_SIZE = 17;

type
  PGtkAccessibleTristate = ^TGtkAccessibleTristate;
  TGtkAccessibleTristate = longint;

const
  GTK_ACCESSIBLE_TRISTATE_FALSE = 0;
  GTK_ACCESSIBLE_TRISTATE_TRUE = 1;
  GTK_ACCESSIBLE_TRISTATE_MIXED = 2;

type
  PGtkAccessibleInvalidState = ^TGtkAccessibleInvalidState;
  TGtkAccessibleInvalidState = longint;

const
  GTK_ACCESSIBLE_INVALID_FALSE = 0;
  GTK_ACCESSIBLE_INVALID_TRUE = 1;
  GTK_ACCESSIBLE_INVALID_GRAMMAR = 2;
  GTK_ACCESSIBLE_INVALID_SPELLING = 3;

type
  PGtkAccessibleAutocomplete = ^TGtkAccessibleAutocomplete;
  TGtkAccessibleAutocomplete = longint;

const
  GTK_ACCESSIBLE_AUTOCOMPLETE_NONE = 0;
  GTK_ACCESSIBLE_AUTOCOMPLETE_INLINE = 1;
  GTK_ACCESSIBLE_AUTOCOMPLETE_LIST = 2;
  GTK_ACCESSIBLE_AUTOCOMPLETE_BOTH = 3;

type
  PGtkAccessibleSort = ^TGtkAccessibleSort;
  TGtkAccessibleSort = longint;

const
  GTK_ACCESSIBLE_SORT_NONE = 0;
  GTK_ACCESSIBLE_SORT_ASCENDING = 1;
  GTK_ACCESSIBLE_SORT_DESCENDING = 2;
  GTK_ACCESSIBLE_SORT_OTHER = 3;

type
  PGtkAccessibleAnnouncementPriority = ^TGtkAccessibleAnnouncementPriority;
  TGtkAccessibleAnnouncementPriority = longint;

const
  GTK_ACCESSIBLE_ANNOUNCEMENT_PRIORITY_LOW = 0;
  GTK_ACCESSIBLE_ANNOUNCEMENT_PRIORITY_MEDIUM = 1;
  GTK_ACCESSIBLE_ANNOUNCEMENT_PRIORITY_HIGH = 2;

type
  PGtkPopoverMenuFlags = ^TGtkPopoverMenuFlags;
  TGtkPopoverMenuFlags = longint;

const
  GTK_POPOVER_MENU_SLIDING = 0;
  GTK_POPOVER_MENU_NESTED = 1 shl 0;


implementation


end.
