/////////////////////////////////////////////////////////////
//                                                         //
//   WARNUNG, dies Datei wird automatisch durch            //
//   das Program "Convert_Unit_to_pas_includes" erzeugt !  //
//   Erzeugt am: 05-08-2024   15:41                        //
//                                                         //
/////////////////////////////////////////////////////////////

{$IFDEF read_interface}

const
  GTK_IM_MODULE_EXTENSION_POINT_NAME = 'gtk-im-module';

{$ENDIF read_interface}


{$IFDEF read_implementation}


{$ENDIF read_implementation}
