SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/11/32/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/cross/lib/i386-linux/")
SEARCH_DIR("/usr/lib/i386-linux-gnu/")
SEARCH_DIR("/lib/i386-linux-gnu/")
SEARCH_DIR("./")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/httpd22/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/sdl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/ibase/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/hermes/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/ptc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/postgres/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-process/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-report/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libpng/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libvlc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-base/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/utmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/oracle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libgc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libffi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libtar/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libmicrohttpd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fastcgi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pthreads/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/ncurses/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gnutls/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-image/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gdbm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/xforms/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/zorba/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/jni/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-fpcunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/cairo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/paszlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/vcl-compat/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/mysql/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libfontconfig/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/mad/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl-generics/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libgd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libusb/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/openal/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/opengles/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-passrc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pastojs/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/oggvorbis/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libenet/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fpmkunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/openssl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/x11/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-res/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/bfd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/bzip2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/imlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/tplylib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fpgtk/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/aspell/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libcups/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/odbc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/symbolic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gtk1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/webidl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-sound/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/numlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libcurl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pasjpeg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gnome1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/cdrom/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/modplug/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-xml/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/a52/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl-unicode/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/iconvenc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/unzip/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl-objpas/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/svgalib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/regexpr/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/chm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libxml2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl-console/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/opengl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/dts/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-web/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/dblib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/opencl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/sqlite/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/zlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/gdbint/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/uuid/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/syslog/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libmagic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-registry/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pcap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fppkg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/lua/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/httpd24/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-db/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/tcl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fpindexer/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/googleapi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-pdf/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fv/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/ggi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libsee/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/libc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/dbus/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-json/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/unixutil/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-sdo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/proj4/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pxlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/newt/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/ldap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fftw/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/graph/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/odata/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-net/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rsvg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/imagemagick/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-async/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/fcl-stl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/users/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_stable/fpc/bin/x86_64-linux/")
INPUT(
/home/tux/fpcupdeluxe_stable/cross/lib/i386-linux/crti.o
/usr/lib/gcc/x86_64-linux-gnu/11/32/crtbegin.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/si_c21.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-1/lazyfoo.net/33_-_Multithreading/lib/i386-linux/Project1.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/system.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/lnfodwrf.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/exeinfo.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/strings.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/objpas.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/ctypes.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/sdl/sdl.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/sdl/sdl_image.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/unixtype.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/types.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/pthreads/pthreads.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/baseunix.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/unix.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/x11/x.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/x11/xlib.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/math.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/sysutils.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/linux.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/errors.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/sysconst.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/unixutil.o
/home/tux/fpcupdeluxe_stable/fpc/units/i386-linux/rtl/initc.o
)
INPUT(
-lSDL
-lSDL_image
-lpthread
-lX11
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/11/32/crtend.o
/home/tux/fpcupdeluxe_stable/cross/lib/i386-linux/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
