/////////////////////////////////////////////////////////////
//                                                         //
//   WARNUNG, dies Datei wird automatisch durch            //
//   das Program "Convert_Unit_to_pas_includes" erzeugt !  //
//   Erzeugt am: 04-08-2024   16:38                        //
//                                                         //
/////////////////////////////////////////////////////////////

{$IFDEF read_interface}


  // === Konventiert am: 3-8-24 15:24:40 ===

type
  TGskPathMeasure = record
  end;
  PGskPathMeasure = ^TGskPathMeasure;

  TGskPath = record
  end;
  PGskPath = ^TGskPath;

type
  TGskRenderer = record
  end;
  PGskRenderer = ^TGskRenderer;

{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
